'use client';
import {useEffect,useMemo,useState} from 'react';
import {KEY,SETTINGS,seed,defaultSettings} from '../data';
import {tr,translations} from '../../lib/i18n';
import {addDays,calendarParts,formatDate,monthDates,monthTitle,weekdayIndex,isoToday} from '../../lib/date';

function sameMonth(a,b,calendar){const x=calendarParts(a,calendar,'en'),y=calendarParts(b,calendar,'en');return x.year===y.year&&x.month===y.month}
function monthStart(iso,calendar){let cur=iso;while(sameMonth(addDays(cur,-1),cur,calendar))cur=addDays(cur,-1);return cur}
function shiftMonth(iso,calendar,dir){const start=monthStart(iso,calendar);return addDays(start,dir===1?32:-1)}

export default function CalendarPage(){
 const[data,setData]=useState(seed),[settings,setSettings]=useState(defaultSettings),[anchor,setAnchor]=useState(isoToday),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[dark,setDark]=useState(false),[mobileOpen,setMobileOpen]=useState(false);
 useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setData(JSON.parse(x));const s=localStorage.getItem(SETTINGS);if(s)setSettings({...defaultSettings,...JSON.parse(s)})}catch{}},[]);
 useEffect(()=>{document.documentElement.lang=settings.language;document.documentElement.dir=translations[settings.language].dir;document.documentElement.classList.toggle('dark',dark);document.documentElement.classList.remove('font-small','font-medium','font-large');document.documentElement.classList.add(`font-${settings.fontSize||'medium'}`);localStorage.setItem('pdp-dark',dark?'1':'0')},[settings,dark]);
 const t=k=>tr(settings.language,k);
 const dates=useMemo(()=>monthDates(anchor,settings.calendar),[anchor,settings.calendar]);
 const first=dates[0];
 const offset=((weekdayIndex(first)-(settings.firstDay==='sunday'?0:6))+7)%7;
 const cells=Array(offset).fill(null).concat(dates);
 const dayTasks=iso=>data.tasks.filter(x=>x.date===iso);
 function choose(iso){setSelected(iso);setModal(dayTasks(iso).length?'day':'add')}
 function deleteTask(id){if(!window.confirm(t('confirmDeleteTask')))return;const next={...data,tasks:data.tasks.filter(x=>x.id!==id).map(x=>({...x,prerequisites:(x.prerequisites||[]).filter(p=>p!==id)}))};setData(next);localStorage.setItem(KEY,JSON.stringify(next));}
 function addTask(e){e.preventDefault();const f=new FormData(e.currentTarget);const type=f.get('scheduleType');const task={id:Date.now(),title:f.get('title'),description:f.get('description')||'',date:selected,priority:f.get('priority'),scheduleType:type,startTime:type==='time'?f.get('startTime'):'',endTime:type==='time'?f.get('endTime'):'',completed:false,activityUnit:f.get('unit')||'مورد',activityValue:0,prerequisites:[]};const next={...data,tasks:[...data.tasks,task]};setData(next);localStorage.setItem(KEY,JSON.stringify(next));setModal('day')}
 return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="brandMark">✓</div><div className="brandText"><b>روزمن</b><span>{t('planner')}</span></div></div><nav className="nav"><a href="/">⌂ <span>{t('today')}</span></a><a className="active" href="/calendar">▦ <span>{t('calendar')}</span></a><a href="/?new=1">＋ <span>{t('newTask')}</span></a><a href="/routines">↻ <span>{t('routines')}</span></a><a href="/?settings=1">⚙ <span>{t('settings')}</span></a></nav></aside>{mobileOpen&&<><div className="drawerBackdrop" onClick={()=>setMobileOpen(false)}/><aside className="mobileDrawer"><div className="brand"><div className="brandMark">✓</div><div className="brandText"><b>روزمن</b><span>{t('planner')}</span></div><button className="drawerClose" onClick={()=>setMobileOpen(false)}>×</button></div><nav className="nav"><a href="/">⌂ <span>{t('today')}</span></a><a className="active" href="/calendar">▦ <span>{t('calendar')}</span></a><a href="/?new=1">＋ <span>{t('newTask')}</span></a><a href="/routines">↻ <span>{t('routines')}</span></a><a href="/?settings=1">⚙ <span>{t('settings')}</span></a></nav></aside></>}<div className="main"><header className="topbar"><div className="topLeft"><button className="mobileMenu" onClick={()=>setMobileOpen(true)}>☰</button><span className="crumb">{t('planner')} / {t('calendar')}</span></div><div className="topActions"><button className="iconBtn" onClick={()=>setDark(v=>!v)}>{dark?'☀':'☾'}</button></div></header><main className="content"><div className="hero"><div><div className="kicker">{t('calendar')}</div><h1>{t('calendarTitle')}</h1><p>{t('calendarSub')}</p></div></div><section className="card calendarWrap"><div className="calendarToolbar"><div className="monthTitle"><h1>{monthTitle(anchor,settings.calendar,settings.language)}</h1><span>{formatDate(anchor,settings.calendar,settings.language,true)}</span></div><div className="monthActions"><button className="ghost" onClick={()=>setAnchor(shiftMonth(anchor,settings.calendar,-1))}>‹ {t('monthPrev')}</button><button className="ghost" onClick={()=>setAnchor(isoToday)}>{t('monthToday')}</button><button className="ghost" onClick={()=>setAnchor(shiftMonth(anchor,settings.calendar,1))}>{t('monthNext')} ›</button></div></div><div className="calGrid">{(settings.firstDay==='sunday'?[0,1,2,3,4,5,6]:[6,0,1,2,3,4,5]).map((d,i)=><div className="calHead" key={i}>{[t('sunday'),t('monday'),t('tuesday'),t('wednesday'),t('thursday'),t('friday'),t('saturday')][d]}</div>)}{cells.map((iso,i)=>iso?<Day key={iso} iso={iso} settings={settings} tasks={dayTasks(iso)} selected={selected===iso} onClick={()=>choose(iso)}/>:<div key={'b'+i} className="calBlank"/>)}</div></section></main><MobileNav lang={settings.language}/></div>
 {modal==='day'&&<Modal title={formatDate(selected,settings.calendar,settings.language)} close={()=>setModal(null)}><div className="calendarTaskList">{dayTasks(selected).map(x=><div className={`calendarTask ${x.completed?'done':''}`} key={x.id} onClick={()=>setModal({type:'details',id:x.id})} role="button" tabIndex={0}><div><b>{x.title}</b><span>{x.completed?'✓ ':''}{x.scheduleType==='time'?`${x.startTime} – ${x.endTime}`:t('day')}</span>{x.description&&<small>{x.description}</small>}</div><div className="calendarTaskActions"><span className={`tag ${x.priority}`}>{x.priority==='essential'?t('essentialLabel'):x.priority==='important'?t('importantLabel'):t('normal')}</span><button type="button" className="miniBtn dangerBtn" onClick={e=>{e.stopPropagation();deleteTask(x.id)}}>×</button></div></div>)}</div><button className="primary full" onClick={()=>setModal('add')}>＋ {t('newTask')}</button></Modal>}
 {modal?.type==='details'&&(()=>{const task=data.tasks.find(x=>x.id===modal.id);return task?<Modal title={t('taskDetails')} close={()=>setModal('day')}><div className="detailGrid"><div><span>{t('title')}</span><b>{task.title}</b></div><div><span>{t('priority')}</span><b>{task.priority==='essential'?t('essentialLabel'):task.priority==='important'?t('importantLabel'):t('normal')}</b></div><div><span>{t('schedule')}</span><b>{task.scheduleType==='time'?`${task.startTime} – ${task.endTime}`:t('day')}</b></div><div><span>{t('status')}</span><b>{task.completed?t('done'):t('remainingStatus')}</b></div></div>{task.description&&<div className="detailDescription"><span>{t('description')}</span><p>{task.description}</p></div>}<button className="ghost full" onClick={()=>setModal('day')}>{t('close')}</button></Modal>:null})()}
 {modal==='add'&&<Modal title={t('addFor',{date:formatDate(selected,settings.calendar,settings.language)})} close={()=>setModal(dayTasks(selected).length?'day':null)}><AddForm lang={settings.language} onSubmit={addTask}/></Modal>}
 </div>
}
function Day({iso,settings,tasks,selected,onClick}){return <button className={`calDay ${selected?'selected':''} ${tasks.length?'hasTasks':''}`} onClick={onClick}><span className="dayNum">{calendarParts(iso,settings.calendar,settings.language).day}</span><div className="dots">{tasks.some(x=>x.priority==='essential')&&<i className="dot r"/>}{tasks.some(x=>x.priority==='important')&&<i className="dot p"/>}{tasks.some(x=>x.completed)&&<i className="dot g"/>}</div>{tasks.length>0&&<span className="count">{tasks.length}</span>}</button>}
function AddForm({lang,onSubmit}){const t=k=>tr(lang,k);const[type,setType]=useState('day');return <form className="form" onSubmit={onSubmit}><label>{t('title')}<input name="title" required autoFocus/></label><label>{t('description')}<textarea name="description" rows="3"/></label><label>{t('priority')}<select name="priority" defaultValue="normal"><option value="normal">{t('normal')}</option><option value="important">{t('importantLabel')}</option><option value="essential">{t('essentialLabel')}</option></select></label><label>{t('schedule')}<select name="scheduleType" value={type} onChange={e=>setType(e.target.value)}><option value="day">{t('day')}</option><option value="time">{t('atTime')}</option></select></label>{type==='time'&&<div className="two timeFields"><label>{t('start')}<input name="startTime" type="time" required/></label><label>{t('end')}<input name="endTime" type="time" required/></label></div>}<label>{t('unit')}<select name="unit"><option>دقیقه</option><option>ساعت</option><option>درصد</option><option>مورد</option><option>صفحه</option></select></label><button className="primary">{t('save')}</button></form>}
function Modal({title,children,close}){return <div className="overlay" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHeader"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function MobileNav({lang}){return <nav className="mobileNav"><a href="/">⌂<span>{tr(lang,'today')}</span></a><a className="active" href="/calendar">▦<span>{tr(lang,'calendar')}</span></a><a href="/?new=1" className="add">+<span>{tr(lang,'newTask')}</span></a><a href="/routines">↻<span>{tr(lang,'routines')}</span></a><a href="/?settings=1">⚙<span>{tr(lang,'settings')}</span></a></nav>}
